# Predict Proba

Investigate the output of the .predict_proba method.

In [5]:
import numpy as np
import sklearn
from sklearn.linear_model import LogisticRegression

In [4]:
X = np.array([[1, 0], [1, 0], [1, 0], [0, 1], [0, 1], [0, 1]])
y = np.array([1, 1, 1, 2, 2, 2])

X, y 

(array([[1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1]]),
 array([1, 1, 1, 2, 2, 2]))

In [10]:
clf = LogisticRegression()

clf.fit(X, y)
p = clf.predict(X)
a = clf.predict_proba(X)

p, a 

(array([1, 1, 1, 2, 2, 2]),
 array([[0.70676257, 0.29323743],
        [0.70676257, 0.29323743],
        [0.70676257, 0.29323743],
        [0.29323743, 0.70676257],
        [0.29323743, 0.70676257],
        [0.29323743, 0.70676257]]))

In [11]:
clf = LogisticRegression()

y2 = np.array([2, 2, 2, 1, 1, 1])
clf.fit(X, y2)
p2 = clf.predict(X)
a2 = clf.predict_proba(X)

p2, a2 

(array([2, 2, 2, 1, 1, 1]),
 array([[0.29323743, 0.70676257],
        [0.29323743, 0.70676257],
        [0.29323743, 0.70676257],
        [0.70676257, 0.29323743],
        [0.70676257, 0.29323743],
        [0.70676257, 0.29323743]]))